name: smart_farming
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sebaiknya gunakan rentang versi seperti ini

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  chopper: ^7.0.0
  json_annotation: ^4.8.1
  built_value: ^8.6.3
  built_collection: ^5.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  permission_handler: ^11.0.0
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Versi terbaru mungkin lebih baik
  build_runner: ^2.4.6
  chopper_generator: ^7.0.0
  json_serializable: ^6.7.1
  built_value_generator: ^8.6.3
  flutter_launcher_icons: '^0.13.1'

flutter:
  uses-material-design: true

# --- TAMBAHKAN BLOK INI ---
# Letakkan di sini, sejajar dengan 'flutter:', 'name:', 'dependencies:'
flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/logo.png' # <-- PASTIKAN PATH INI BENAR
  min_sdk_android: 21
# ---------------------------
